export const styles = {
    sidebarArea: { flex: 1, display: 'flex', flexDirection: 'column', gap: '15px' },
    panelCard: { background: '#1e293b', padding: '25px', borderRadius: '20px', border: '1px solid #334155' },
    hS: { color: '#38bdf8', fontSize: '0.8rem', textTransform: 'uppercase', margin: '20px 0 10px 0', fontWeight: 'bold' },
    lC: { fontSize: '0.65rem', color: '#64748b', fontWeight: 'bold', display: 'block', marginBottom: '5px' },
    selS: { width: '100%', background: '#0f172a', border: '1px solid #334155', padding: '10px', color: '#fff', borderRadius: '8px', marginBottom: '15px', outline: 'none', fontSize: '0.8rem' },
    btnM: { background: '#0f172a', border: '1px solid #334155', color: '#94a3b8', padding: '10px', borderRadius: '6px', cursor: 'pointer', fontSize: '0.7rem' },
    actB: { background: '#38bdf8', border: '1px solid #334155', color: '#0f172a', padding: '10px', borderRadius: '6px', cursor: 'pointer', fontSize: '0.7rem', fontWeight: 'bold' },
    clrI: { width: '100%', height: '35px', background: 'none', border: '1px solid #334155', cursor: 'pointer', borderRadius: '4px' },
    btnSave: { width: '100%', background: '#34d399', color: '#0f172a', padding: '14px', borderRadius: '10px', fontWeight: 'bold', border: 'none', cursor: 'pointer' },
    btnMain: { width: '100%', background: '#38bdf8', color: '#0f172a', border: 'none', padding: '16px', borderRadius: '12px', fontWeight: 'bold', cursor: 'pointer', marginTop: '10px' },
    btnReset: { width: '100%', background: 'none', border: '1px solid #f87171', color: '#f87171', padding: '10px', borderRadius: '10px', fontSize: '0.75rem', cursor: 'pointer', marginTop: '20px' },
    paperWrapper: { flex: '3', minWidth: '0', background: '#334155', padding: '40px 10px', borderRadius: '15px', display: 'flex', flexDirection: 'column', alignItems: 'center', overflowX: 'auto' },
    paperS: { background: '#fff', color: '#000', padding: '20mm 15mm', display: 'flex', flexDirection: 'column', minHeight: '297mm', boxShadow: '0 0 60px rgba(0,0,0,0.5)', width: '210mm' },
    titleI: { fontSize: '2.5rem', fontWeight: '900', textTransform: 'uppercase', width: '100%' },
    areaI: { fontSize: '0.85rem', color: '#475569', height: '55px', resize: 'none', width: '100%' },
    headerG: { display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #000', paddingBottom: '15px' },
    mR: { display: 'flex', justifyContent: 'flex-end', gap: '8px', fontSize: '0.8rem', marginBottom: '3px' },
    mInp: { width: '90px', textAlign: 'right', borderBottom: '1px solid #eee !important' },
    tagL: { fontSize: '0.7rem', fontWeight: 'bold', color: '#94a3b8' },
    tableS: { width: '100%', borderCollapse: 'collapse', marginTop: '20px' },
    thS: { textAlign: 'left', padding: '10px 8px', fontSize: '0.75rem', color: '#64748b', textTransform: 'uppercase' },
    tdS: { padding: '10px 8px', borderBottom: '1px solid #f1f5f9' },
    rawI: { fontSize: '0.85rem', width: '100%', border: 'none', outline: 'none', background: 'transparent' },
    addB: { width: '100%', padding: '10px', background: '#f8fafc', border: '1px dashed #ccc', cursor: 'pointer', marginTop: '15px', color: '#94a3b8', fontSize: '0.7rem' },
    sumR: { display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: '0.85rem' },
    toastS: { position: 'fixed', top: '20px', right: '20px', background: '#34d399', color: '#0f172a', padding: '15px 30px', borderRadius: '12px', fontWeight: 'bold', zIndex: 100000 },
    colList: { background: '#0f172a', padding: '15px', borderRadius: '15px' },
    colItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', gap: '8px', borderBottom: '1px solid #1e293b', paddingBottom: '8px' },
    ghB: { background: 'none', border: 'none', color: '#38bdf8', cursor: 'pointer', fontSize: '0.7rem' },
    ghI: { background: 'none', border: '1px solid #334155', color: '#fff', fontSize: '0.7rem', padding: '5px', borderRadius: '4px' },
    chargeItem: { display: 'flex', gap: '8px', marginBottom: '10px', alignItems: 'center' },
    searchI: { background: '#f8fafc', border: '1px solid #e2e8f0', padding: '15px', borderRadius: '12px', width: '100%', fontSize: '0.8rem', color: '#000', marginBottom: '15px' },
};