import React from 'react';
import ToolboxLayout from '../../components/ToolboxLayout';

export default function Terms() {
  return (
    <ToolboxLayout
      title="Terms of Use"
      description="Read the terms of use for SHB ToolBox, including acceptable use, tool limitations, privacy-first processing, and user responsibilities."
    >
      <section style={pageWrap}>
        <div style={card}>
          <p style={eyebrow}>Legal Information</p>
          <h1 style={title}>Terms of Use</h1>
          <p style={muted}>Last updated: June 1, 2026</p>

          <p style={para}>
            Welcome to SHB ToolBox. By using this website, you agree to use our free online tools responsibly and in accordance with these terms. SHB ToolBox is provided as a collection of browser-based utilities for productivity, finance, image processing, text formatting, calculations, and general digital tasks.
          </p>

          <h2 style={h2}>1. Use of Our Tools</h2>
          <p style={para}>
            Our tools are designed for general informational and productivity purposes. You may use them for personal, educational, freelance, and business workflows. You must not use this website for illegal activity, harmful automation, abuse of third-party systems, or attempts to interfere with the security or availability of the site.
          </p>

          <h2 style={h2}>2. Accuracy and User Responsibility</h2>
          <p style={para}>
            We work to make SHB ToolBox accurate and useful, but results generated by calculators, converters, invoice tools, image tools, and text tools should be reviewed before being used for important decisions. For financial, tax, legal, medical, or compliance-related matters, you should verify outputs with a qualified professional or official source.
          </p>

          <h2 style={h2}>3. Client-Side Processing</h2>
          <p style={para}>
            Many SHB ToolBox utilities are designed to run directly inside your browser. This means that files, text, images, and calculation inputs are generally processed locally on your device unless a specific feature clearly requires an external service. We aim to keep tools privacy-first and avoid unnecessary storage of user data.
          </p>

          <h2 style={h2}>4. Intellectual Property</h2>
          <p style={para}>
            The SHB ToolBox website design, written content, interface elements, and tool structure are owned by SHB ToolBox / SHB Stores unless otherwise stated. You may use outputs created by the tools for your own work, but you may not copy, resell, or republish the website itself as a competing service.
          </p>

          <h2 style={h2}>5. Third-Party Services and Advertising</h2>
          <p style={para}>
            SHB ToolBox may display advertising or use third-party services to support the free availability of our tools. Third-party services may operate under their own policies. We do not control third-party websites linked from this site.
          </p>

          <h2 style={h2}>6. Availability and Changes</h2>
          <p style={para}>
            We may update, improve, remove, or change tools and content at any time. We do not guarantee that every tool will always be available, error-free, or suitable for every specific use case.
          </p>

          <h2 style={h2}>7. Contact</h2>
          <p style={para}>
            For questions about these terms, contact us at <strong>support@shbstores.com</strong>.
          </p>
        </div>
      </section>
    </ToolboxLayout>
  );
}

const pageWrap = { maxWidth: '950px', margin: '0 auto', padding: '60px 20px' };
const card = { background: '#1e293b', border: '1px solid #334155', borderRadius: '24px', padding: '40px', lineHeight: 1.8 };
const eyebrow = { color: '#38bdf8', textTransform: 'uppercase', fontSize: '0.8rem', fontWeight: 800, letterSpacing: '0.08em' };
const title = { fontSize: '2.6rem', margin: '10px 0', color: '#fff' };
const muted = { color: '#94a3b8', marginBottom: '30px' };
const h2 = { color: '#fff', fontSize: '1.35rem', marginTop: '30px', marginBottom: '10px' };
const para = { color: '#cbd5e1', fontSize: '1rem', marginBottom: '16px' };
